### ISSUE TITLE
<elm-accordion-body> doesn't handle that the content changes height

### ISSUE THREAD

**Issue by hanshenrik** [hallelujahdrive/elm-accordion#1]
First off – great package! Very easy to use, love it!

However, we've encountered a problem when we have content with conditional rendering of elements. The height of `<elm-accordion-body>` doesn't change when the height of the content inside it changes. Would it be possible to make the height adjust based on the height of the content? Not sure how listening to changes to the content height would affect performance, but I guess that might be a possible solution?

![2021-02-16 16-00-14 2021-02-16 16_02_58](https://user-images.githubusercontent.com/3757042/108080713-749c9900-7070-11eb-8c25-68792017addc.gif)

**Comment by hanshenrik** [comment]
Perhaps [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) can be used to monitor any changes to height/width of the head/body? See e.g. https://stackoverflow.com/a/39312522/6303323

**Comment by hallelujahdrive** [comment]
Hi @hanshenrik,  thank you for your contribution!

I fixed the bug in https://github.com/hallelujahdrive/elm-accordion/commit/e48c14e645436150c1c4792cc4a710f2da946628 .
Please update `elm-accorordion` on your project to version 1.0.3. 

Sure, `ResizeObserver` can help solve this problem, but it's often an exaggerated solution.
I modified it as follows: If the content of the `elm-accordion-body` changes, the height of the accordion will change, but it will not animate. 
This behaves like a [bootstrap accordion](https://getbootstrap.com/docs/5.0/components/accordion/).

If you want to animate height changes as the content changes, you'll need `ResizeObserver`, as you say. 

I hope this bug fix helps you.
