### ISSUE TITLE
Flicker on page load

### ISSUE THREAD

**Issue by hanshenrik** [hallelujahdrive/elm-accordion#2]
Sorry to bother you again, but I was wondering if you might have any tricks up your sleeve to prevent the accordion body content from "flickering" when the page is loaded.

Ellie example: https://ellie-app.com/crSbK4spfcma1

In the Ellie example, the JS and CSS files are imported in the `<head>` (importing the script in the `<body>` doesn't seem to make a difference), but in my project I've imported them using bundler (required at the top of the `index.js` file). The flicker seems to happen regardless of how the JS/CSS are imported. It also seems to happen both when running a dev server (e.g. `elm-app start`) and when serving a built application.

Tested on macOS in Chrome, Firefox, Safari and Edge (beta)

![2021-02-22 15-48-33 2021-02-22 15_49_09](https://user-images.githubusercontent.com/3757042/108724368-875a1680-7525-11eb-86ff-0f68a3d1ce84.gif)

**Comment by hanshenrik** [comment]
Adding `.elm-accordion__body { height: 0; }` to the `<style>` tag in the Ellie example seems to fix the problem, but when I add this to the CSS file in our project (which is bundled by Webpack) it only seems to improve the flicker a little bit. There's still a little bit of flickering.

**Comment by hallelujahdrive** [comment]
Hi @hanshenrik ,
I was probably able to solve this problem in #3.

I have confirmed that there are no problems with the drawing of the [demo page](https://hallelujahdrive.github.io/elm-accordion) of this project and your [Ellie](https://ellie-app.com/crSbK4spfcma1), but I have not tested it exhaustively so please let me know immediately if you have any problems.

Thank you very much for using this product.

**Comment by hanshenrik** [comment]
Works great for our cases 🎉 Thanks for the quick response!
